version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: chatroom_development
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  # backend:
  #   build: ./backend
  #   ports:
  #     - "3001:3000"
  #   depends_on:
  #     - db
  #   environment:
  #     DATABASE_URL: postgres://postgres:postgres@db:5432/chatroom_development
  #   volumes:
  #     - ./backend:/app
  #   command: bash -c "rm -f tmp/pids/server.pid && rails server -b '0.0.0.0'"

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - ./frontend:/app
    command: npm start

  aqa:
    build: ./aqa
    depends_on:
      - frontend
    environment:
      CYPRESS_baseUrl: http://frontend:3000
    volumes:
      - ./aqa:/e2e
    command: npm start

volumes:
  pgdata:
