version: '3.8'

services:
  redis:
    extends:
      file: ./backend/.docker/development/redis.yml
      service: redis

  db:
    extends:
      file: ./backend/.docker/development/db.yml
      service: db

  backend:
    extends:
      file: ./backend/.docker/development/development.yml
      service: backend

  frontend:
    extends:
      file: ./frontend/.docker/development/development.yml
      service: frontend

  aqa:
    extends:
      file: ./aqa/.docker/development/development.yml
      service: aqa

volumes:
  pgdata:
