# backend/.docker/development/production.yml
version: '3.8'

services:
  redis:
    image: redis:6.2
    ports:
      - "6379:6379"
  sidekiq:
    build:
      context: ../../
      dockerfile: .docker/production/Dockerfile
    environment:
      RAILS_ENV: production
      REDIS_URL: redis://redis:6379/1
    volumes:
      - ../../:/rails
    depends_on:
      - redis
      - db
    command: bundle exec sidekiq -C config/sidekiq.yml
  backend:
    build:
      context: ../../
      dockerfile: .docker/production/Dockerfile
    environment:
      RAILS_ENV: production
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      DATABASE_URL: ${DATABASE_URL}
      POSTGRES_PORT: ${POSTGRES_PORT}
      RAILS_SECRET_KEY_BASE: ${RAILS_SECRET_KEY_BASE}
    ports:
      - "3001:3000"
    volumes:
      - ../../:/rails
    depends_on:
      - db
    command: bash -c "rm -f tmp/pids/server.pid && rails server -b '0.0.0.0'"
