version: '3.8'

services:
  aqa:
    build:
      context: ../../
      dockerfile: .docker/production/Dockerfile
    volumes:
      - ../results:/app/results
    environment:
      - NODE_ENV=production
      - PORT=3002
      - CYPRESS_BASE_URL=${CYPRESS_BASE_URL}
      - CYPRESS_SUPPORT_FILE=cypress/support/index.js
      - CYPRESS_FIXTURES_FOLDER=cypress/fixtures
      - CYPRESS_VIDEOS_FOLDER=cypress/videos
      - CYPRESS_SCREENSHOTS_FOLDER=cypress/screenshots
    depends_on:
      - backend
      - frontend
    command: node server.js
    ports:
      - "3002:3002"
  labels:
    - "traefik.http.routers.aqa.rule=Host(`aqa.qa-challenge.dan1d.dev`)"
    - "traefik.http.routers.aqa.entrypoints=websecure"
    - "traefik.http.routers.aqa.tls=true"
    - "traefik.http.routers.aqa.service=aqa"
    - "traefik.http.services.aqa.loadbalancer.server.port=3002"
    - "traefik.http.routers.aqa-ws.rule=Host(`aqa.qa-challenge.dan1d.dev`)"
    - "traefik.http.routers.aqa-ws.entrypoints=websecure"
    - "traefik.http.routers.aqa-ws.tls=true"
    - "traefik.http.routers.aqa-ws.service=aqa"
    - "traefik.http.services.aqa-ws.loadbalancer.server.port=3002"
    - "traefik.http.routers.aqa-ws.headers.customrequestheaders.Connection=Upgrade"
    - "traefik.http.routers.aqa-ws.headers.customrequestheaders.Upgrade=websocket"
