version: '3.8'

services:
  aqa:
    build:
      context: ../../
      dockerfile: .docker/production/Dockerfile
    volumes:
      - ../results:/app/results
    environment:
      - NODE_ENV=production
      - CYPRESS_BASE_URL=${CYPRESS_BASE_URL}
      - CYPRESS_SUPPORT_FILE=cypress/support/index.js
      - CYPRESS_FIXTURES_FOLDER=cypress/fixtures
      - CYPRESS_VIDEOS_FOLDER=cypress/videos
      - CYPRESS_SCREENSHOTS_FOLDER=cypress/screenshots
    depends_on:
      # - backend
      # - frontend
    command: node server.js
    labels:
      - "traefik.http.routers.backend.rule=Host(`aqa.qa-challenge.dan1d.dev`)"
      - "traefik.http.routers.backend.entrypoints=websecure"
      - "traefik.http.routers.backend.tls=true"
      - "traefik.http.routers.backend.tls.certresolver=myresolver"
      - "traefik.http.services.backend.loadbalancer.server.port=3005"
      - "traefik.http.middlewares.websocket-headers.headers.customrequestheaders.Connection=Upgrade"
      - "traefik.http.middlewares.websocket-headers.headers.customrequestheaders.Upgrade=websocket"
      - "traefik.http.routers.backend.middlewares=websocket-headers"
