version: '3.8'

services:
  aqa:
    build:
      context: ../../
      dockerfile: .docker/production/Dockerfile
    volumes:
      - ../results:/app/results
    environment:
      - NODE_ENV=production
      - CYPRESS_BASE_URL=${CYPRESS_BASE_URL}
      - CYPRESS_SUPPORT_FILE=cypress/support/index.js
      - CYPRESS_FIXTURES_FOLDER=cypress/fixtures
      - CYPRESS_VIDEOS_FOLDER=cypress/videos
      - CYPRESS_SCREENSHOTS_FOLDER=cypress/screenshots
    ports:
      - "3005:3005"
    depends_on:
      # - backend
      # - frontend
    command: node server.js
    labels:
      - "traefik.http.routers.aqa.rule=Host(`aqa.qa-challenge.dan1d.dev`)"
      - "traefik.http.routers.aqa.entrypoints=websecure"
      - "traefik.http.routers.aqa.tls=true"
      - "traefik.http.routers.aqa.tls.certresolver=myresolver"
      - "traefik.http.services.aqa.loadbalancer.server.port=3005"

      # # WebSocket handling for WebSocket connections
      # - "traefik.http.routers.aqa-ws.rule=Host(`aqa.qa-challenge.dan1d.dev`) && PathPrefix(`/ws`)"  # Update the PathPrefix to match your WebSocket routes
      # - "traefik.http.routers.aqa-ws.entrypoints=websecure"
      # - "traefik.http.routers.aqa-ws.tls=true"
      # - "traefik.http.services.aqa-ws.loadbalancer.server.port=3005"
      # - "traefik.http.middlewares.websocket-headers.headers.customrequestheaders.Connection=Upgrade"
      # - "traefik.http.middlewares.websocket-headers.headers.customrequestheaders.Upgrade=websocket"
      # - "traefik.http.routers.aqa-ws.middlewares=websocket-headers"
