version: '3.8'

services:
  frontend:
    build:
      context: ../../
      dockerfile: .docker/development/Dockerfile
    environment:
      - NODE_ENV=development
    ports:
      - "3000:3000"
    volumes:
      - ../../:/app
