---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/register":
    post:
      summary: Creates a user
      tags:
      - Users
      parameters: []
      responses:
        '201':
          description: user created
        '422':
          description: invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                display_name:
                  type: string
                password:
                  type: string
              required:
              - email
              - password
  "/login":
    post:
      summary: Logs in a user
      tags:
      - Users
      parameters: []
      responses:
        '200':
          description: user logged in
        '401':
          description: invalid credentials
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
              required:
              - email
              - password
  "/profile":
    get:
      summary: Retrieves the user profile
      tags:
      - Users
      security:
      - bearerAuth: []
      responses:
        '200':
          description: profile retrieved
        '401':
          description: unauthorized
    put:
      summary: Updates the user profile
      tags:
      - Users
      security:
      - bearerAuth: []
      parameters: []
      responses:
        '200':
          description: profile updated
        '422':
          description: invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                display_name:
                  type: string
                password:
                  type: string
                avatar_url:
                  type: string
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
