version: '3.8'

services:
  frontend:
    build:
      context: ../../
      dockerfile: .docker/production/Dockerfile
      args:
        - REACT_APP_BACKEND_URL=${REACT_APP_BACKEND_URL}
        - REACT_APP_AQA_URL=${REACT_APP_AQA_URL}
        - RAILS_CABLE=${RAILS_CABLE}
        - REACT_APP_AQA_WS_URL=${REACT_APP_AQA_WS_URL}
    environment:
      - REACT_APP_BACKEND_URL=${REACT_APP_BACKEND_URL}
      - REACT_APP_AQA_URL=${REACT_APP_AQA_URL}
      - RAILS_CABLE=${RAILS_CABLE}
      - REACT_APP_AQA_WS_URL=${REACT_APP_AQA_WS_URL}
    labels:
      - "traefik.http.routers.frontend.rule=Host(`app.qa-challenge.dan1d.dev`)"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.routers.frontend.tls=true"
      - "traefik.http.routers.frontend.tls.certresolver=myresolver"
      - "traefik.http.services.frontend.loadbalancer.server.port=3000"
