version: '3.8'

services:
  frontend:
    build:
      context: ../../
      dockerfile: .docker/production/Dockerfile
    labels:
      - "traefik.http.routers.frontend.rule=Host(`app.qa-challenge.dan1d.dev`)"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.routers.frontend.tls=true"
      - "traefik.http.routers.frontend.tls.certresolver=myresolver"
      - "traefik.http.services.frontend.loadbalancer.server.port=3000"
